# Generated by Django 6.0.2 on 2026-02-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_job_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employer',
        ),
    ]
